[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-gehri.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

# Add bootloader configuration
[package.metadata.bootloader]
map-physical-memory = true 